@Egs.Api_HostAddress = https://localhost:7110

### List plugins
GET {{Egs.Api_HostAddress}}/api/plugins

### Get Valheim plugin definition
GET {{Egs.Api_HostAddress}}/api/plugins/valheim

### Create Valheim server
POST {{Egs.Api_HostAddress}}/api/servers
Content-Type: application/json

{
  "name": "EGS Valheim",
  "gameKey": "valheim",
  "nodeName": "Local",
  "installPath": ""
}

### List servers
GET {{Egs.Api_HostAddress}}/api/servers
